Movieproject/Movieproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieApp.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Movieproject/movieApp/urls.py
from django.urls import path
from . import views
app_name = 'movieApp'

urlpatterns = [
    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')

]

Movieproject/movieApp/models.py
from django.db import models

# Create your models here.
class movie(models.Model):
       name=models.CharField(max_length=256)
       description=models.TextField()
       year=models.IntegerField()
       image=models.ImageField(upload_to="pics")

       def __str__(self):
           return self.name

Movieproject/movieApp/forms.py
from django import forms
from . models import movie

class MovieForm(forms.ModelForm):
    class Meta:
        model=movie
        fields=['name','description','year','image']

Movieproject/movieApp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from .forms import MovieForm
from . models import movie

# Create your views here.
def index(request):
    movien=movie.objects.all()
    context={
        'movie_list':movien
    }
    return render(request,'index.html',context)

def detail(request,movie_id):
    movies = movie.objects.get(id=movie_id)
    return render(request,'detail.html',{'movie':movies})

def add_movie(request):
    if request.method == 'POST':
        name=request.POST.get('name')
        description=request.POST.get('description')
        year=request.POST.get('year')
        image=request.FILES['image']
        movies1=movie(name=name,description=description,year=year,image=image)
        print(movies1)
        movies1.save()
        return redirect('/')
    return render(request,'add.html')

def update(request,id):
    movieval=movie.objects.get(id=id)
    forms=MovieForm(request.POST or None,request.FILES,instance=movieval)
    if forms.is_valid():
        forms.save()
        return redirect('/')
    return render(request,'edit.html',{'forms':forms,'movie':movieval})

def delete(request,id):
    if request.method == 'POST':
        movievall=movie.objects.get(id=id)
        movievall.delete()
        return redirect('/')
    return render(request,'delete.html')

Movieproject/movieApp/templates/add.html
{% extends 'base.html'%}
{%block body %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}<br><br>
    <label for="name">Name</label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <input type="text" name="name"/><br><br>
    <label for="description">Description</label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <textarea rows="3" name="description"></textarea><br><br><br>
    <label for="image">Image</label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <input type="file" name="image"/><br><br>
    <label for="year">Year</label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
     <input type="text" name="year"/><br>
    <input class="btn btn-primary" type="submit"/>
</form>
{%endblock%}

Movieproject/movieApp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>welcome</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="#">
    Movie Catalogue
  </a>
</nav>
{% block body%}
{% endblock %}

</body>
</html>

Movieproject/movieApp/templates/delete.html
<form method="post">
{%csrf_token%}
Are you sure you want to delete it
<input type="submit"/>
</form>

Movieproject/movieApp/templates/detail.html
{% extends 'base.html'%}
{%block body%}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.image.url}}" width="150" height="150"/>
        </div>
        <div class="col-md-6">
            <dl>

                <dt>{{movie.name}}</dt>
                <dd>{{movie.description}}</dd>
                 <dd>{{movie.year}}</dd>
            </dl>
            <p>
                <a class="btn btn-primary" href="{% url 'movieApp:update' movie.id  %}" >Update Movie</a>

                <a class="btn btn-primary" href="{% url 'movieApp:delete' movie.id  %}" >Delete Movie</a>
            </p>
        </div>
    </div>
</div>


{%endblock%}

Movieproject/movieApp/templates/edit.html
<form method="post" enctype="multipart/form-data">
  {%csrf_token%}
  {{forms.as_p}}
  <input type="submit"/>
</form>

Movieproject/movieApp/templates/index.html
{% extends 'base.html'%}
{%block body%}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <p class="text-right"><a class="btn btn-primary" href="{% url 'movieApp:add_movie' %}">+Add Movie</a></p>
        </div>
    </div>
    <div class="row">

     {%for i in movie_list%}
        <div class="col-sm-3">
            <div class="card" style="width: 180px;height:100px;">
                <img class="card-img-top" src="{{i.image.url}}" alt="Card image cap" ">
                <div class="card-body">
                    <h5 class="card-title">{{i.name}}</h5>
                    <p class="card-text" style="height:50px;overflow:hidden" >{{i.description}}</p>
                    <a href="{% url  'movieApp:detail' i.id %}" class="btn btn-primary">View Details</a>
                </div>
            </div>
        </div>
        {%endfor%}
    </div>

</div>




{%endblock%}